import lc3b_types::*;

module cpu_check_stall
(
   /* Stalls generated by the memory interface */
   input    logic i_mem_resp,				// is the instruction cache currently processing?
	input		logic	d_mem_resp,				//	is the data cache currently processing?
	input		logic	mem_instr,				// are we doing a memory instruction that involves stalls?
	input 	logic d_read,

	output	logic	stall_all				//	STALL PIPELINE WHILE WE ARE WAITING FOR MEMORY
);
   
always_comb

	begin

      stall_all = (!d_mem_resp && mem_instr) || !i_mem_resp;

	
	end
	
	
	
endmodule : cpu_check_stall